name: Django CI/CD

on:
  push:
    branches: [ master, development, test ]
  pull_request:
    branches: [ master, development, test ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: pos-menu
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: as251292
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres -d pos-menu"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: menu_engineering.settings_test
      DATABASE_NAME: pos-menu
      DATABASE_USER: postgres
      DATABASE_PASSWORD: as251292
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in $(seq 1 10); do
          pg_isready -h localhost -p 5432 -U postgres && break
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done
    

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

  deploy-dev:
    if: github.ref == 'refs/heads/development'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to AWS (Dev)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        # Add your AWS deployment commands for developmentment here

  deploy-test:
    if: github.ref == 'refs/heads/test'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to AWS (Test)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        # Add your AWS deployment commands for testing here

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to AWS (Production)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        # Add your AWS deployment commands for production here